### ISSUE TITLE
multiple commits with a True 'validated_bugfix' label - for the same Issue

### ISSUE THREAD

**Issue by Ahmedfir** [smartshark/pycoSHARK#12]
Dear admins,

I am planning to use the smart_shark_2_2 dataset in my current project and I am facing a minor issue:
When loading the `Issues` from the dataset and their fixing commits, I am noticing that half of the issues (4117) have more than 1 fix-commit or do not have a corresponding `CommitChanges` entry.
I wanted to ask you if this is a bug or an expected outcome? Or probably I am doing something wrong?
Here's how I am loading the data:

      git_repo = [repo for repo in VCSSystem.objects(repository_type='git')]
      for repo in git_repo:
          project = Project.objects(id=repo.project_id).get()
          pid = project.name
          issue_trackers = IssueSystem.objects(project_id=project.id).all()
          for issue_tracker in issue_trackers:
              issues = Issue.objects(issue_system_id=issue_tracker.id).all()
              for issue in issues:
                  if issue.issue_type is not None and issue.issue_type_verified is not None and issue.issue_type.lower() == 'bug' and issue.issue_type_verified.lower() == 'bug':
                      bid = issue.external_id
                      fix_commits_query = Commit.objects(linked_issue_ids=issue.id)
                      bug_fixing_commits = set()
                      for commit in fix_commits_query:
                          if commit.labels is not None and 'validated_bugfix' in commit.labels and commit.labels[
                              'validated_bugfix']:
                              bug_fixing_commits.add(commit.id)
                      if len(bug_fixing_commits) != 1 or CommitChanges.objects(
                              new_commit_id=list(bug_fixing_commits)[0]).count() != 1:
                          log.info('ignored {0}'.format(bid))
                          continue

I have another question to which I couldn't find a concrete answer: what is the difference between the big and small release artefacts? Is there the same number of projects and issues in both samples?

Thank you for sharing this fantastic work! 

Best regards

**Comment by atrautsch** [comment]
Hi @Ahmedfir,
thank you for your interest in our work.
The commit has different link types to issues. linked_issue_ids are basically mentioned issues within the commit message.
There is also fixed_issue_ids which has a bug focus. However, it is not uncommon that multiple commits are linked to one issue.
The difference between the small and bigger releases is the inclusion of the code_entity_states which contain source code metrics for every revision. The number of projects is the same.

**Comment by Ahmedfir** [comment]
Hi @atrautsch,

Thank you for your time and your quick answer.

1) Indeed, there're `fixed_issue_ids` and `linked_issue_ids`. When using `fixed_issue_ids` instead of  `linked_issue_ids`, I am still facing this issue (4121 issues have more than 1 fix-commit or do not have a corresponding CommitChanges entry). 
2) Perfect thanks, then I will continue using the small db.

Best regards

**Comment by atrautsch** [comment]
Hi @Ahmedfir,
that is not unreasonable, we have a lot of fixes over multiple commits and probably a lot of issues with no linked commits.
The data was mined at a specific date and issues may also be open / unresolved if there was no fix attempt yet.
Also, issue_type_verified is only available for the projects that were part of manual issue type validation used here: [Problems with SZZ and Issues](https://link.springer.com/article/10.1007/s10664-021-10092-4).

Can you tell me more about what you are trying to achieve?

**Comment by atrautsch** [comment]
Hi @Ahmedfir,
thats interesting, we currently have a student that works on a defects4j compatible tooling to extract this information from the smartshark database. Depending on the rest of your tooling you could also use repository_data which contains the git snapshot of the project at the time of the mining to extract the full state of the repository before and after the fix in the same fashion as defects4j.
Be aware that you will most likely encounter tangled changes. For a subset of projects we have data from our [tangling study](https://arxiv.org/abs/2011.06244) that contains information about which line most likely contributed to the bug fix.

**Comment by Ahmedfir** [comment]
Hi @atrautsch,

Great news! I think it will be very useful! 
The repository_data is in the big released version (file to download)? I downloaded the small one and I am cloning and checking out stuff on the fly, probably that's why I don't have it.
Yes! my supervisor has sent me the paper already and recommended the dataset. Great work by the way! ;)

Thanks for your time and support!
